version: "3.5"

services:
  app:
    image: ${REGISTRY_URL}/${CONTAINER_NAME}-dev-app:${APP_VERSION}.${BUILD_NUMBER}
    container_name: ${CONTAINER_NAME}-dev-app
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        HTTP_PROXY:  ${HTTP_PROXY}
    env_file: .env
    restart: always
    ports:
      - target: 9876
        published: ${DOMAIN_PORT}
        protocol: tcp
        mode: host